version: '3.3'
services:
    mysqldb:
        image: mysql
        restart: always
        environment:
          - MYSQL_ROOT_PASSWORD=
          - MYSQL_USER=${USER}
          - MYSQL_PASSWORD=${PASSWORD}
          - MYSQL_DATABASE=Rilevazioni
          - MYSQL_ALLOW_EMPTY_PASSWORD=yes
          - MYSQL_TCP_PORT=${MYSQL_PORT}
        volumes: 
          - ./sql/DB.sql:/docker-entrypoint-initdb.d/DB.sql          
    web-node:
        build: .
        ports:
          - ${EXTERNAL_PORT}:${PORT}
        environment:
          - PORT=${PORT}
          - EXTERNAL_PORT=${EXTERNAL_PORT}
          - HOST=${HOST}
          - USERNAME=${USER}
          - PASSWORD=${PASSWORD}
          - MYSQL_PORT=${MYSQL_PORT}
          - SECRET_KEY=${SECRET_KEY}
        depends_on:
          - mysqldb
        command: ['./wait-for-it/wait-for-it.sh', 'mysqldb:${MYSQL_PORT}', '--timeout=100000', '--', 'node', 'index.js']
