version: '3.3'
services:
    mysqldb:
        image: mysql
        restart: always
        environment:
          - MYSQL_ROOT_PASSWORD=${PASSWORD}
          - MYSQL_DATABASE=${DATABASE}
          - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        ports:
          - ${MYSQL_PORT}:${EXTERNAL_DB_PORT}
        volumes: 
          - ./sql/DB.sql:/docker-entrypoint-initdb.d/DB.sql          
    web-node:
        build: .
        ports:
          - ${PORT}:${EXTERNAL_PORT}
        environment:
          - PORT=${PORT}
          - HOST=${HOST}
          - DATABASE=${DATABASE}
          - USERNAME=${USER}
          - PASSWORD=${PASSWORD}
          - MYSQL_PORT=${MYSQL_PORT}
          - SECRET_KEY=${SECRET_KEY}
        depends_on:
          - mysqldb
